### ISSUE TITLE
Site is not secured when trying to access https://cssa-aei.ca

### ISSUE THREAD

**Issue by stephaniegiang** [CSSA-AEI/cssa-web#3]
When switching to Github Pages HTTPS, when accessing https://cssa-aei.ca it says the site is unsecured. However, when accessing cssa-aei.ca and www.cssa-aei.ca it works just fine. Believe this is due to the configuration on the DNS side. 

Will take a look at this.

**Comment by obenn** [comment]
Secured by Let's Encrypt
